name: format

on:
  push:
    paths:
      - "**/*"
    branches:
      - main
  pull_request:
    paths:
      - "**/*"
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Prettier
        run: |
          echo '{
            "semi": false,
            "singleQuote": true,
            "tabWidth": 2,
            "printWidth": 120,
            "plugins": [
              "prettier-plugin-java",
              "prettier-plugin-kotlin"
            ]
          }' > .prettierrc
          echo '*.min.*
          .github/**/*
          *-min.*
          *.xml' > .prettierignore

      - name: Install Prettier with plugins
        run: |
          npm i -D prettier prettier-plugin-java prettier-plugin-kotlin

      - name: Format all files
        run: |
          npx prettier -w **/*.{java,md,kt,json,md}
          find . -type f -name "*.xml" -exec java -jar devAssets/android-xml-formatter.jar --indention 2 --attribute-indention 2 {} \;

      - name: Clean up unnecessary files
        run: |
          rm -rf node_modules
          rm -f package.json
          rm -f package-lock.json
          rm -f .prettierrc
          rm -f .prettierignore

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "auto-format" || echo "No changes to commit"
          git push
